language: r
cache: packages

os: 
  - osx
  - linux
  - windows

r_github_packages:
  - jimhester/lintr
  - jimhester/covr
  - MangoTheCat/goodpractice

after_success:
  # - Rscript -e 'lintr::lint_package()'
  - travis_wait 120 Rscript codecov.R;
  # - travis_wait 60 Rscript -e 'library(goodpractice); gp()'
